volumes:
  virtuoso_data:
  postgres_data:

services:
  postgres:
    image: postgres:17-alpine
    container_name: climatesense-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-climatesense_cache}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-climatesense_cache}",
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: climatesense-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@climatesense-project.eu}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-8082}:80"
    depends_on:
      - postgres
    restart: unless-stopped

  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    container_name: climatesense-virtuoso
    env_file: .env
    environment:
      DBA_PASSWORD: ${VIRTUOSO_PASSWORD:-dba}
      SPARQL_UPDATE: true
    ports:
      - "${VIRTUOSO_PORT:-8890}:8890"
    volumes:
      - virtuoso_data:/database
      - ./virtuoso/initdb.d:/initdb.d:ro
      - ../data:/database/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8890/sparql || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  isql-service:
    build:
      context: ./isql-service
      dockerfile: Dockerfile
    container_name: climatesense-isql
    environment:
      VIRTUOSO_HOST: virtuoso
      VIRTUOSO_ISQL_PORT: 1111
      VIRTUOSO_USER: dba
      VIRTUOSO_PASSWORD: ${VIRTUOSO_PASSWORD:-dba}
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "${ISQL_SERVICE_PORT:-8080}:8080"
    depends_on:
      - virtuoso
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: climatesense-pipeline
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-climatesense_cache}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      VIRTUOSO_HOST: virtuoso
      VIRTUOSO_PORT: 8890
      VIRTUOSO_USER: dba
      VIRTUOSO_PASSWORD: ${VIRTUOSO_PASSWORD:-dba}
      VIRTUOSO_ISQL_SERVICE_URL: http://isql-service:8080
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../cache:/app/cache
      - ../config:/app/config:ro
      - ${CIMPLE_MODELS_PATH:-../data/cimple-factors-models}:/app/data/cimple-factors-models
    depends_on:
      - virtuoso
      - isql-service
      - postgres
    profiles:
      - manual
