PREFIX schema: <http://schema.org/>
PREFIX cimple: <http://data.cimple.eu/ontology#>

SELECT (COUNT(?review) AS ?totalReviews)
       (COUNT(?author) AS ?reviewsWithAuthor)
       (COUNT(?rating) AS ?reviewsWithRating)
       (COUNT(?normalizedRating) AS ?reviewsWithNormalizedRating)
WHERE {
  ?review a schema:ClaimReview .
  OPTIONAL { ?review schema:author ?author . }
  OPTIONAL { ?review schema:reviewRating ?rating . }
  OPTIONAL { ?review cimple:normalizedReviewRating ?normalizedRating . }
}
