PREFIX dcat:    <http://www.w3.org/ns/dcat#>

SELECT ?graph (COUNT(*) AS ?tripleCount)
WHERE {
  {
    GRAPH <http://data.climatesense-project.eu/graph/catalog> {
      ?catalog dcat:dataset ?graph .
    }
  }
  UNION
  {
    BIND(<http://data.climatesense-project.eu/graph/catalog> AS ?graph)
  }
  GRAPH ?graph {
    ?s ?p ?o
  }
}
GROUP BY ?graph
ORDER BY DESC(?tripleCount)
