data_sources:
  - name: "claimreviewdata"
    type: "claimreviewdata"
    provider:
      provider_type: "github"
      repository: "MartinoMensio/claimreview-data"
      mode: "release"
      asset_pattern: "*.zip"
      extract_file: "claim_reviews.json"
  - name: "euroclimatecheck"
    type: "euroclimatecheck"
    provider:
      provider_type: "github"
      repository: "climatesense-project/euroclimatecheck-scraper"
      mode: "release"
      asset_pattern: "all_articles.json"
  - name: "defacto"
    type: "defacto"
    provider:
      provider_type: "xwiki"
      base_url: "https://defacto-observatoire.fr"
      tags: ["Climat", "climat", "Changement climatique"]
  - name: "dbkf"
    type: "dbkf"
    provider:
      provider_type: "graphql"
      endpoint: "https://dbkf.ontotext.com/gql-api"
      query: |
        query GetReviewsWithConcepts($limit: PositiveInteger!, $offset: NonNegativeInteger!) {
          claimReview(
            limit: $limit,
            offset: $offset,
            where: {
              OR: [
                { annotation: { concept: { id: { EQ: "http://weverify.eu/resource/Concept/Q7937" } } } },
                { annotation: { concept: { id: { EQ: "http://weverify.eu/resource/Concept/Q7942" } } } },
                { annotation: { concept: { id: { EQ: "http://weverify.eu/resource/Concept/Q125928" } } } }
              ]
            }
          ) {
            id
            externalUrl
            headline
            reviewBody
            author {
              id
              name
            }
            publisher {
              id
              name
            }
            language
            dateCreated
            annotation {
              concept {
                id
                prefLabel {
                  value
                }
              }
              description
            }
            containsEvent {
              startOffset
              endOffset
              text
              eventType {
                id
              }
              hasTrigger {
                startOffset
                endOffset
                text
              }
            }
            imageObject {
              image
            }
            audioObject {
              audio
            }
            videoObject {
              video
            }
            fileObject {
              file
            }
            itemReviewed {
              id
              text
            }
            hasPart {
              about
            }
          }
        }
      batch_size: 100
  - name: "desmog"
    type: "desmog"
    provider:
      provider_type: "github"
      repository: "climatesense-project/climate-disinformation-database"
      mode: "repository"
      repository_path: "graphs/climate-disinformation-database.ttl"
      repository_ref: "main"
      timeout: 120
  - name: "climafacts"
    type: "climafacts"
    provider:
      provider_type: "github"
      repository: "climatesense-project/climafacts-kg"
      mode: "release"
      asset_pattern: "climafacts_kg.ttl"
      timeout: 120

# Enrichment configuration
enrichment:
  url_text_extraction:
    enabled: true
    rate_limit_delay: 0
    timeout: 15
    max_retries: 2

  dbpedia_spotlight:
    enabled: true
    api_url: "https://api.dbpedia-spotlight.org/en/annotate"
    confidence: 0.6
    support: 30
    timeout: 20
    rate_limit_delay: 0

  bert_factors:
    enabled: true
    batch_size: 64
    max_length: 128
    timeout: 300
    rate_limit_delay: 0

# Output configuration
output:
  format: "nt"
  output_path: "data/rdf/{DATE}/{SOURCE}_{DATETIME}.nt"
  base_uri: "http://data.climatesense-project.eu"

# Cache configuration
cache:
  cache_dir: "cache"
  default_ttl_hours: 24.0

# Deployment configuration
deployment:
  virtuoso:
    enabled: true
    graph_template: "http://data.climatesense-project.eu/graph/{SOURCE}"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/daily_pipeline.log"
  max_file_size: "50MB"
  backup_count: 10
